import appConfig from '../../app.config';

import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * The permission surface the app declares.
 *
 * `EnvironmentInput` calls `Location.requestForegroundPermissionsAsync()`. On iOS,
 * doing that without `NSLocationWhenInUseUsageDescription` terminates the app at
 * the request and fails App Store review -- and nothing else in the repo catches
 * its absence, because the native projects are generated by `expo prebuild` and are
 * not committed. See issue #44.
 */
const resolve = (env?: string): ExpoConfig => {
  const previous = process.env.APP_ENV;
  if (env === undefined) delete process.env.APP_ENV;
  else process.env.APP_ENV = env;
  try {
    return appConfig({ config: {} } as unknown as ConfigContext);
  } finally {
    if (previous === undefined) delete process.env.APP_ENV;
    else process.env.APP_ENV = previous;
  }
};

const pluginNames = (config: ExpoConfig): string[] =>
  (config.plugins ?? []).map((plugin) =>
    typeof plugin === 'string' ? plugin : (plugin[0] as string)
  );

describe('location permission declarations', () => {
  const config = resolve('production');

  it('declares the iOS when-in-use usage description', () => {
    const description = config.ios?.infoPlist?.NSLocationWhenInUseUsageDescription;
    expect(typeof description).toBe('string');
    expect((description as string).length).toBeGreaterThan(40);
  });

  it('says what is collected, where it is kept and that exports include it', () => {
    const description = (
      config.ios?.infoPlist?.NSLocationWhenInUseUsageDescription as string
    ).toLowerCase();

    expect(description).toContain('altitude');
    expect(description).toContain('latitude');
    expect(description).toContain('this device');
    expect(description).toContain('export');
  });

  it('registers the expo-location plugin', () => {
    expect(pluginNames(config)).toContain('expo-location');
  });

  it('declares Android location permissions explicitly', () => {
    expect(config.android?.permissions).toEqual([
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.ACCESS_FINE_LOCATION',
    ]);
  });

  it('does not request background location on either platform', () => {
    const locationPlugin = (config.plugins ?? []).find(
      (plugin) => Array.isArray(plugin) && plugin[0] === 'expo-location'
    ) as [string, Record<string, unknown>];

    expect(locationPlugin[1].isIosBackgroundLocationEnabled).toBe(false);
    expect(locationPlugin[1].isAndroidBackgroundLocationEnabled).toBe(false);
    expect(locationPlugin[1].locationAlwaysPermission).toBe(false);
    expect(locationPlugin[1].locationAlwaysAndWhenInUsePermission).toBe(false);
  });
});

describe('permissions the app has no code to use', () => {
  const config = resolve('production');

  it('blocks camera, media and audio permissions on Android', () => {
    expect(config.android?.blockedPermissions).toEqual(
      expect.arrayContaining([
        'android.permission.CAMERA',
        'android.permission.READ_MEDIA_IMAGES',
        'android.permission.READ_EXTERNAL_STORAGE',
        'android.permission.RECORD_AUDIO',
        'android.permission.SYSTEM_ALERT_WINDOW',
      ])
    );
  });

  it('actually deletes the placeholders, not just registers a plugin', () => {
    // The registration assertion below says the plugin is wired up; this says it
    // does its job. Expo's bare template seeds these six, and a `false` in
    // `ios.infoPlist` does not remove them -- only a withInfoPlist mod does.
    // Exercising the mod directly means an Expo change to its semantics fails
    // here rather than silently restoring six unearned permission strings to a
    // shipped build.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const withTrimmedIosPermissions = require('../../plugins/withTrimmedIosPermissions');

    const seeded = {
      NSLocationWhenInUseUsageDescription: 'Real, and must survive',
      NSLocationAlwaysUsageDescription: 'Allow $(PRODUCT_NAME) to access your location',
      NSLocationAlwaysAndWhenInUseUsageDescription: 'Allow $(PRODUCT_NAME) …',
      NSCameraUsageDescription: 'Allow $(PRODUCT_NAME) to access your camera',
      NSPhotoLibraryUsageDescription: 'Allow $(PRODUCT_NAME) to access your photos',
      NSPhotoLibraryAddUsageDescription: 'Allow $(PRODUCT_NAME) …',
      NSMicrophoneUsageDescription: 'Allow $(PRODUCT_NAME) to access your microphone',
      NSMotionUsageDescription: 'Allow $(PRODUCT_NAME) to access your device motion',
      CFBundleName: 'Mobile DOPE',
    };

    // withInfoPlist(config, mod) hands the mod a config whose modResults is the
    // merged plist. Capture the mod and run it against the seeded template.
    let captured: ((modConfig: { modResults: Record<string, unknown> }) => unknown) | undefined;
    jest.isolateModules(() => {
      jest.doMock('expo/config-plugins', () => ({
        withInfoPlist: (config: unknown, mod: typeof captured) => {
          captured = mod;
          return config;
        },
      }));
      // eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
      const plugin = require('../../plugins/withTrimmedIosPermissions');
      plugin({});
    });

    expect(typeof captured).toBe('function');
    const modResults: Record<string, unknown> = { ...seeded };
    (captured as (m: { modResults: Record<string, unknown> }) => unknown)({ modResults });

    expect(Object.keys(modResults).filter((k) => k.endsWith('UsageDescription'))).toEqual([
      'NSLocationWhenInUseUsageDescription',
    ]);
    // Non-permission keys are untouched.
    expect(modResults.CFBundleName).toBe('Mobile DOPE');
    expect(withTrimmedIosPermissions).toBeDefined();
  });

  it('runs the plugin that strips the iOS template placeholders', () => {
    // Expo's bare template seeds camera/photo/microphone/motion strings that a
    // `false` in `ios.infoPlist` does not remove.
    expect(pluginNames(config)).toContain('./plugins/withTrimmedIosPermissions');
  });

  it('declares no usage description other than when-in-use location', () => {
    const keys = Object.keys(config.ios?.infoPlist ?? {}).filter((key) =>
      key.endsWith('UsageDescription')
    );
    expect(keys).toEqual(['NSLocationWhenInUseUsageDescription']);
  });
});

describe('config resolves for every build profile', () => {
  it.each(['development', 'staging', 'production'])('resolves APP_ENV=%s', (env) => {
    const config = resolve(env);
    expect(config.ios?.infoPlist?.NSLocationWhenInUseUsageDescription).toBeDefined();
    expect(config.android?.permissions).toBeDefined();
  });
});
